### PR TITLE
Remove deprecated ioutil package.

### PR DESCRIPTION
**Pull request by robdimsdale**
## Summary

Remove references to now-deprecated `ioutil` package.

## Checklist

* [x] I have viewed, signed, and submitted the Contributor License Agreement.
* [ ] I have linked issue(s) that this PR should close using keywords or the Github UI (See [docs](https://docs.github.com/en/github/managing-your-work-on-github/linking-a-pull-request-to-an-issue))
* [x] I have added an integration test, if necessary.
* [x] I have reviewed the [styleguide](https://github.com/paketo-buildpacks/community/blob/main/STYLEGUIDE.md) for guidance on my code quality.
* [x] I'm happy with the commit history on this PR (I have rebased/squashed as needed).

### CODE REVIEW

**Comment by robdimsdale** [comment]
I see that the `create-stack` test is failing, but I am not able to re-trigger it and it's not obvious to me that this failure is related to my PR.

**Comment by robdimsdale** [comment]
I think it's related to #82

**Comment by sophiewigmore** [comment]
@robdimsdale right, the issue is with authenticating when the PR is a fork. Unfortunately the workaround is to point the PR at a non-main branch, merge it in, and then open a new PR from workaround branch to main.

**Comment by robdimsdale** [comment]
@sophiewigmore given that, any objections to merging this?

**Review by brayanhenao — APPROVED** [review]

**Comment by brayanhenao** [comment]
@robdimsdale I merge this pr into an intermediate branch since the authentication steps don't work from forks.

**Pull request merged**
