### PR TITLE
Add `zlib1g` package to the tiny stack.

### LINKED ISSUE #76: Implement Stacks RFC 0002
Stacks RFC [0002](https://github.com/paketo-buildpacks/rfcs/blob/main/text/stacks/0002-add-libz.md) was accepted, so we should implement this according to specifications in the RFC.

- [ ] Tiny Run Image contains the libz package

### PR DESCRIPTION
**Pull request by dmikusa**
## Summary
Implements [Paketo Stacks RFC 0002](https://github.com/paketo-buildpacks/rfcs/blob/main/text/stacks/0002-add-libz.md) based on the conversation [here](https://github.com/paketo-buildpacks/rfcs/pull/79#issuecomment-867064231).

## Use Cases
To implement RFC 0002.

## Checklist

* [x] I have viewed, signed, and submitted the Contributor License Agreement.
* [x] I have linked issue(s) that this PR should close using keywords or the Github UI (See [docs](https://docs.github.com/en/github/managing-your-work-on-github/linking-a-pull-request-to-an-issue))
* [x] I have added an integration test, if necessary.
* [x] I have reviewed the [styleguide](https://github.com/paketo-buildpacks/community/blob/main/STYLEGUIDE.md) for guidance on my code quality.
* [x] I'm happy with the commit history on this PR (I have rebased/squashed as needed).

### CODE REVIEW

**Comment by dmikusa** [comment]
I'm not sure why my PR failed the test. The failure is regarding `docker login`, so I'm assuming it's something with my PR & how it was submitted from a fork, but idk exactly. If it requires any changes, please let me know. Thanks!

**Review by sophiewigmore — CHANGES_REQUESTED** [review]
Can you please update the tiny/dockerfile/run/README file to include `zlib1g`?

**Comment by sophiewigmore** [comment]
@dmikusa-pivotal RE: why the docker login failed, ~~I don't think GHA wants us to do logins like that anymore and the test hasn't run in a few months. I'll put in [a PR](https://github.com/paketo-buildpacks/stacks/pull/79) to fix it~~

This has to do with the secrets not getting passed when triggered from a forked repo. We might need to do some messing around to get this to work. cc @brayanhenao

**Comment by dmikusa** [comment]
> Can you please update the tiny/dockerfile/run/README file to include `zlib1g`?

Should be all set now. Thanks

**Comment by brayanhenao** [comment]
Replaced with #81

**Pull request closed without merging**
