### PR TITLE
Arm64 support

### PR DESCRIPTION
**Pull request by darylrobbins**
paketo-buildpacks/stacks#51

## Summary

Build arm64 images for all stacks. Unfortunately, Github Actions does not currently support arm64 workers, but I have tested locally.

## Use Cases

Running on arm64.

## Checklist

* [X] I have viewed, signed, and submitted the Contributor License Agreement.
* [X] I have linked issue(s) that this PR should close using keywords or the Github UI (See [docs](https://docs.github.com/en/github/managing-your-work-on-github/linking-a-pull-request-to-an-issue))
* [X] I have added an integration test, if necessary. (not supported by Github Actions today)
* [X] I have reviewed the [styleguide](https://github.com/paketo-buildpacks/community/blob/main/STYLEGUIDE.md) for guidance on my code quality.
* [X] I'm happy with the commit history on this PR (I have rebased/squashed as needed).

### CODE REVIEW

**Comment by sophiewigmore** [comment]
@darylrobbins thank you for your contribution! I'll check it out and see what next steps are. I would imagine we will need an [RFC](https://github.com/paketo-buildpacks/rfcs) to formally propose supporting the ARM64 stack, and codify what will be needed. Also tagging @dmikusa-pivotal and @ryanmoran here as well.

**Comment by dmikusa** [comment]
This is awesome, thanks!

+1 for an RFC. I think that would give us a chance to pull together a list of all the pieces that would need to be modified and create a plan on how we move forward together so that we can claim ARM64 support. The individual language teams can then use that to make sure they're following the right path.

**Comment by sophiewigmore** [comment]
@darylrobbins looking through your changes I don't see many test updates. Is it possible to add some to our acceptance tests if possible, or any of the `create-stack` tests?

**Comment by sophiewigmore** [comment]
@darylrobbins looking through your changes I don't see many test updates. Is it possible to add some to our acceptance tests if possible / any of the create-stack tests?

**Comment by darylrobbins** [comment]
I can create them but not sure how we'll be able to run them as part of the pipeline without an arm64 build agent.

**Comment by sophiewigmore** [comment]
Ah true. I worry about eventually publishing and supporting stacks that we can't test first in a public-facing manner

**Comment by darylrobbins** [comment]
@sophiewigmore Is there any possibility of setting up a self-hosted runner for the project that runs on arm64? GitHub Actions does support arm64 for self-hosted runners.

**Comment by sophiewigmore** [comment]
According to https://github.blog/changelog/2019-12-03-github-actions-self-hosted-runners-on-arm-architectures/ we should be able to set something up.. Although this is the first time I've ever looked into it. The Cloud Native Buildpacks project has some stuff set up [here](https://github.com/buildpacks/ci/tree/bf663fca3d2817cb4cc9e981caba832209b12a15/gh-runners/ubuntu-arm64) through Equinix Metal we might be able to leverage

**Comment by robdimsdale** [comment]
We are going to archive this repo so we will close this issue.

Supporting arm architectures is on our roadmap. We have also extracted the `create-stack` code from this repo into a new `jam create-stack` command (see [here](https://github.com/paketo-buildpacks/jam/blob/main/commands/create_stack.go)), so that's where any future changes will go.

**Pull request closed without merging**
